name: Build & Deploy to Nomad 

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: 
      - 'self-hosted' 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 'Build gitprofile'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true 
          tags: ghcr.io/ebarriosjr/gitprofile:v0.0.1
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 'Install nomad'
        run: |
          apt-get update
          apt-get install -y wget gpg coreutils
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install -y nomad 

      - name: 'Deploy'
        uses: 'ebarriosjr/nomad-deploy-action@v1'
        env:
          NOMAD_ADDR: http://192.168.1.162
          NOMAD_PORT: 4646
          NOMAD_JOB: 'gitprofile.hcl'
